### PR TITLE
Fix bug with btrfs & qemu (64K vs 4K pages)

### PR DESCRIPTION
**Pull request by Sadoon-AlBader**
Most modern Linux distros are using 64K pages, using 4K makes some filesystems, (through my testing mainly btrfs) unusable in those systems, and in the case of my Talos II, unbootable. QEMU also complains unless you specifically set this:

`<features>
    <hpt resizing="required">
      <maxpagesize unit="KiB">4</maxpagesize>
    </hpt>
</features>`
Changing over to 64K pages:
1- Makes Void-ppc's filesystems compatible with other distributions of Linux (tried Ubuntu, Fedora, and a bit of Alpine, all use 64K)
2- Makes QEMU+Libvirt work out of the box.
3- Makes btrfs bootable (at least on the Talos II build I'm using, the filesystem isn't even detected before the change, probably because the built-in bootloader runs Linux with 64K pages as well.)

I only proposed the change for 5.6 because that is what I tested, I simply changed the setting, compiled, installed, and booted the new kernel. Works flawlessly with btrfs now. Feel free to change the older kernels as well.

### CODE REVIEW

**Comment by q66** [comment]
https://docs.voidlinux-ppc.org/faq/index.html#why-use-4-kib-page-kernels-instead-of-64-kib-like-other-distros

The decision to use 4kB pages is intentional. Btrfs should fix their stuff instead (besides, I hear it's pretty unreliable and wastes resources on 64k either way, and btrfs filesystems created on 64k are not mountable on e.g. x86 and so on because they all use 4k pages). There are multiple workarounds for qemu issues, also addressed in the FAQ.

As far as I know, there are no other problematic filesystems.

There are also no other distro compatibility concerns, you can boot virtual machines with 64k pages on 4k hosts just fine.

If you want to boot btrfs root on a Talos 2, you can always use a `/boot` partition with a different filesystem, too.

**Comment by Sadoon-AlBader** [comment]
Thank you, this points me in a good direction, I'll try to separate boot from / and see if that works.
And that FAQ is very informative.

**Comment by q66** [comment]
I think that's the way to go for the time being, since as i mentioned, btrfs created on a 4 KiB system should perform better either way, and you won't have as limited recovery options (can stick the drive in an x86 system and still have it work and so on, and even when recovering on a Talos 2, can always use a 4k based live system, VM etc.)

I might add an xbps-src build option for 64k kernels for people who really want it, but the default binaries should stay on 4k, I don't see a need to be the same as other distros, Void was never one to strictly follow the same conventions as the others, and unlike other distros, we're the first modern LE distro to primarily target desktop use.

**Comment by Sadoon-AlBader** [comment]
> we're the first modern LE distro to aim primarily target desktop use.

Yeah tell me about it. Ubuntu's Firefox has been broken for at least months now. You have to compile your own, and some packages there are outright broken.
So far I liked Void-ppc so much that I switched all my x86 devices to Void too :)
It honestly beats even Arch in simplicity and speed.

**Pull request closed without merging**
