### PR TITLE
socat: use different termios bits for ppc

### PR DESCRIPTION
**Pull request by ghost**
Socat currently fails on ppc due to wrong termios bits.

### CODE REVIEW

**Comment by q66** [comment]
Indeed, you're right. Please drop the newline escaping in the strings though, also sub-indent with 1 space, like this:

```
	ppc*)
		configure_args+="
		 sc_cv_sys_crdly_shift=12
		 sc_cv_sys_tabdly_shift=10
		 sc_cv_sys_csize_shift=8"
		;;
	*)
		configure_args+="
		 sc_cv_sys_crdly_shift=9
		 sc_cv_sys_tabdly_shift=11
		 sc_cv_sys_csize_shift=4"
		;;
```

Also, since the package is orphaned, feel free to assign maintainer to me (`q66 <daniel@octaforge.org>`), unless you want to pick it up yourself, of course.

**Comment by ghost** [comment]
Oh well, it wasn't supposed to come from my master branch. But I fixed the lines that you mentioned.

**Comment by q66** [comment]
Thanks. I put it in my local staging tree, updated packages as well as repo will come out with the next batch, as will an upstream `void-packages` submission.

**Comment by ghost** [comment]
Should I just do PRs for your staging branch in the future or simply upstream? I think I saw you doing bigger batches from time to time.

**Comment by q66** [comment]
You can just go upstream and tag me if you want, in which case it will be pulled into the repo with other upstream changes - here is also alright though. Depends on which way is more comfortable for you (upstream repo needs more setting up for building packages as it does not have void-ppc repo paths and so on)

**Pull request closed without merging**
