### PR TITLE
newbluemoon’s additions

### PR DESCRIPTION
**Pull request by newbluemoon**
Note: This PR is for the ppc-foxlet branch.

I think the main difference is that I enabled secure-plt where available.
See “Q: My dynamically linked program crashes on PowerPC!” in musl’s [FAQ](https://wiki.musl-libc.org/faq.html).

Affected packages are binutils, gcc, gdb, and cross-powerpc-linux-musl. However, I didn’t touch cross-powerpc-linux-gnu, but I think it should be enabled there, too (if we agree to it).
**Edit:** Or I could make it conditionally, ppc-musl only.

In the build-/cross-profile I used `-mtune=powerpc` instead of `-mcpu=powerpc`. Don’t know what’s better (if they’re not synonym).

Also, I’m not really sure which `XBPS_TRIPLET` to use: of the existing some have `-unknown-` in them, others not.

I noticed that Alpine uses `--disable-decimal-float` in their [powerpc-gcc](https://git.alpinelinux.org/cgit/aports/tree/main/gcc/APKBUILD). <s>Not sure why.</s>
**Edit:** Removed it for this PR at first, because it’s not used for glibc ppc, but a ppc-musl test build without it failed, so I added it again.

### CODE REVIEW

**Comment by newbluemoon** [comment]
@foxlet @stenstorp Did you have a chance to look at my proposed additions/changes? As I don’t have Telegram maybe this way we could discuss this?

I’ve been trying to get yaboot working for ppc-musl, but I’m not sure this is even possible (for musl).

**Comment by stenstorp** [comment]
Might merge your changes first then and put the others on top. I'll tell the others and see what they think.

**Comment by newbluemoon** [comment]
@stenstorp I didn’t merge yet because I thought it’d be easier to review each single addition first and make alterations if necessary. Also I’m hesitant to merge into @foxlet’s branch without his agreement. :)

**Comment by stenstorp** [comment]
Why are you merging with foxlets branch? I thought we were merging to master.

**Comment by newbluemoon** [comment]
@stenstorp It’s just that I had some things @foxlet also did so I removed them in this PR to not have something double (but maby slightly different). Also he had much more packages fixed. I regarded his branch as a reference, because I think we need one base we can make changes to. And when making a real PR I think it’s better to have it in a branch rather than master.

Your commits are alright, but I think we should use proper naming, Void-style like. ;)
`<pkgname>: <change>`

**Comment by newbluemoon** [comment]
I’m not really sure how guys intended how this should work. Just let me know where I should push. :)
Maybe we should create a new branch where we merge everything together and work on that one from then on?

**Comment by stenstorp** [comment]
Fair enough. Is he OK with you merging to his branch?
Also, Can I rename a commit or do I have to do it again?

**Comment by newbluemoon** [comment]
I don’t know if he’s ok, that’s why I didn’t merge. @foxlet please let us know your opinion on this. :)

@stenstorp With `git rebase -i ...` you can pick commits you’d like to rename.

**Comment by stenstorp** [comment]
I've been using the github webpage for all this. I guess I should probably learn how to use the terminal stuff.

**Comment by newbluemoon** [comment]
That’s always a good idea. :) I know the basic stuff, nothing too fancy. But the more you work with it the better you get at it.

**Comment by newbluemoon** [comment]
@stenstorp I modified the commit names, I think it’s ok now.

**Comment by stenstorp** [comment]
There's now a proper branch for to commit to, merging into there.

**Comment by newbluemoon** [comment]
Alright, thanks! :)

**Pull request merged**
